### ISSUE TITLE
Update ntuples content

### ISSUE THREAD

**Issue by jbsauvan** [PFCal-dev/cmssw#121]
* [x] Update gen ntuple with information similar to those in the reco ntuples:
  - Propagation information
  - fbrem
  - etc.
* [x] Add TC sim energy
* [x] Change layer variables to cover the full detector (and not only a given subdet)\
* [ ] Add flags to switch between ntuples with different levels of details and sizes
* [x] Improve the association between TC, clusters and multiclusters
* Add TC neighbours?

**Comment by naodell** [comment]
Would you be open to adding panel information to the trigger cell ntuple process.  In an earlier version of the ntuple code, rather than using the panel_tc_* branches, I had added two branches to HGCalTriggerNtupleHGCTriggerCells.cc:

```
tree.Branch("tc_panel_number", &tc_panel_number_);
tree.Branch("tc_panel_sector", &tc_panel_sector_);
```

Those seemed sufficient to do everything I wanted to do for the purpose of algorithm testing since a lot of variables associated with the panel are shared with the trigger cell.

Also, I would be interested in helping with implementing TC neighbors if that's still outstanding.

**Comment by jbsauvan** [comment]
Hi @naodell 
Sure, you can make a PR adding the panel information to the TC ntuple and I will merge it.
Also, yes, it would be great if you could implement the TC neighbor information in the ntuples, this has not been done yet.
Thanks!

**Comment by naodell** [comment]
Sounds good.  I just updated to do some testing of PR 206 (https://github.com/PFCal-dev/cmssw/pull/206).  Is that a good starting point?

**Comment by jbsauvan** [comment]
The merging of this PR will not be done before a few weeks, so it is better to base developments on the standard devel branch `hgc-tpg-devel-CMSSW_10_2_0_pre5`.

**Comment by naodell** [comment]
Will do.
