### ISSUE TITLE
STC containing 0 TC 

### ISSUE THREAD

**Issue by jbsauvan** [PFCal-dev/cmssw#409]
Appearing in CMSSW 11_0_0_pre11. Was fine in CMSSW 11_0_0_pre10.
It seems that some STC have 0 TC, which gives an exception in https://github.com/PFCal-dev/cmssw/blob/hgc-tpg-devel-CMSSW_11_0_0_pre10/L1Trigger/L1THGCal/src/concentrator/HGCalConcentratorSuperTriggerCellImpl.cc#L42-L46

**Comment by snwebb** [comment]
The problem is as follows:
When the list of TC IDs within a STC are determined, a check is performed that the IDs are valid:
https://github.com/PFCal-dev/cmssw/blob/eb44f4ecb4dfc987541d58e449a9f41934ed95ef/L1Trigger/L1THGCal/src/HGCalCoarseTriggerCellMapping.cc#L196

The issue is that one of the invalid TCs was the one that originally was used to determine the superTC ID.
So the TC was already invalid when passed to the selection algorithm here: https://github.com/PFCal-dev/cmssw/blob/eb44f4ecb4dfc987541d58e449a9f41934ed95ef/L1Trigger/L1THGCal/plugins/concentrator/HGCalConcentratorProcessorSelection.cc#L128

I don't know if this is the expected behaviour?
From the SuperTC side I think the code is fine, because one would assume that the initial list of TCs included only valid IDs.

**Comment by jbsauvan** [comment]
I indeed saw in recent geometry testing I did, that some invalid cells were produced.

So in the case of STC, is it robust when invalid TCs are given? Will it just discard these TCs and behave as if they don't exist?

**Comment by snwebb** [comment]
If it is not guaranteed that all incoming TCs are valid, then I guess it is best to add a validity check here: https://github.com/PFCal-dev/cmssw/blob/eb44f4ecb4dfc987541d58e449a9f41934ed95ef/L1Trigger/L1THGCal/src/concentrator/HGCalConcentratorSuperTriggerCellImpl.cc#L175 
Then no STC is created from an invalid cell, and therefore there is at least 1 valid cell per STC.

**Comment by jbsauvan** [comment]
Actually, I think it would be even better to filter the valid cells in the VFE, before the TCs are created.

I'll take care of this. But first I need to check what exactly these invalid cells are. It is weird that we get those.

**Comment by jbsauvan** [comment]
So these invalid cells are located at the edges of the detector:
![image](https://user-images.githubusercontent.com/5569798/69794189-203a9e80-11ca-11ea-808c-147f36b2e6ea.png)

This comes from a fix of the cell validity check brought by  #28129. As mentioned in this PR:

> Earlier the validity of a cell was incomplete. So some silicon cells were declared valid though they were not. This affects cells at the edges in the so called virtual wafers. So some difference is expected.

So it means that running on old digi samples will give these invalid cells since they were considered valid when the sample was produced.

I will add a validity check before the TCs are formed.
